### ISSUE TITLE
Demon NOK

### ISSUE THREAD

**Issue by Bkevin16** [mika-nt28/Jeedom-motion#113]
Bonjour Mika
j'ai relancé une jeedom mini afin de faire tourner le plugin motion et ainsi libérer un peu de ressource sur mon jeedup.
l'ennuie c'est que je n'arrive pas à lancer le deamon, il reste en NOK. J'ai installé plusieurs fois les dépendances, j'ai vérifié l'adresse ip mais c'est toujours NOK
dans les log j'ai ça "sudo: motion: command not found"
je pense que c'est un manque de droit quelque part mais je n'ose pas trop touché.
Sur ma jeedup, l'installation et l'activation du deamon se sont fait sans problème
merci d'avance

**Comment by mika-nt28** [comment]
Bonjour
Est ce que le soucis est regler?

Le demon est nok tant qu'une camera n'est pas configuré et fonctionnel bien sur
par contre visiblement tu as quand meme un probleme d'installation de dependance
A tu regarder sur community j'ai deja aidé des personne avec des probleme similaire
Est d'allieur possible de rester sur le forum communautaire

**Comment by Bkevin16** [comment]
j'ai reinstallé une mini propre (pas une sauvegarde) mais le plugin est
trop gourmand et me la plante au bout d'une dizaine d'heure
je vais tester d'installer ça sur un pi4 voir si c'est mieux
je t'ai envoyé la demande via github car c'est ce que propose le ticket
dous jeedom

Le ven. 8 nov. 2019 à 13:58, Halbout Michael <notifications@github.com> a
écrit :

**Comment by mika-nt28** [comment]
Oui c'est vrai mais maintenant le forum community est plus adapté a ce genre de gestion et permet a d'autre de resoudre eglament leur probleme

Oui motion est assez gourmande, mais cela depend du flux configuré.
Plus il est rapide et pixelisé plus la machine aurra besoin de ressources

**Comment by Bkevin16** [comment]
ok merci micka
pour toi le pi4 est une bonne idée ?

Le ven. 8 nov. 2019 à 14:29, Halbout Michael <notifications@github.com> a
écrit :

**Comment by mika-nt28** [comment]
Si tu le met sur SSD y a des bon retour.
Par contre sur SD je ne le conseil pas du tout

Tu as beaucoup de camera?
Tes flux sont configurable?

**Comment by Bkevin16** [comment]
j'ai pour le moment 3 cameras mais j'aimerai en rajouter deux ou trois de
plus
le flux peut etre envoyé en hd ou en low definition
j'ai reolink RLC 410

Le ven. 8 nov. 2019 à 14:47, Halbout Michael <notifications@github.com> a
écrit :
