### ISSUE TITLE
Problème de Port

### ISSUE THREAD

**Issue by MarcOlivierChaubet** [mika-nt28/Jeedom-motion#28]
Bonjour, 
je rencontre un problème avec le stream.
Il n'y a pas le port dans la requête.
`[DEBUG] : Impossible d'ouvrir le flux video http://192.168.100.112:/stream.mjpg`
Pourtant j'ai bien le port dans la configuration:
```
Adresse ou motion est installé :
192.168.100.112
Port ou motion est installé :
8080
Emplacement du dossier Snapshot :
/var/www/html/tmp/motion
Taille du dossier Snapshot de chaque camera (Mo) :
100

```
Besoin d'aide

**Comment by mika-nt28** [comment]
Bonjour,

Ton problème de port est situé au niveau du stream de ta camera par motion.
il faut que tu te rende sur la page de paramétrage de ta camera motion et que dans l'onglet stream tu sélectionne un port.
C'est un point sur lequel je travail pour rendre automatique ce sujet

**Comment by MarcOlivierChaubet** [comment]
Re,
Je pense que j'ai besoin d'aide pour configurer ton plugin.
En fait si tu regardes c’était des requetes vers l'ip du jeedom, pas de la camera.
On peut se parler au téléphone si tu veux.

**Comment by mika-nt28** [comment]
Oui jeedom restream le flux de la camera pour la visualisé et la tu n'a pas le port de configurer

**Comment by mika-nt28** [comment]
Met a jour le plugin, j'avais forcé l’utilisation de l'url streamé lors d'un essai et oublier de toute enlevé.

Néanmoins pour l'affichage du flux je te conseil grandement de paramètre le stream de motion qui permet d'avoir une image moins belle mais plus légère a affiché

**Comment by MarcOlivierChaubet** [comment]
Bonjour, 
petit topos:
-J'arrive bien à enregistrer et faire des détections sur les cameras
-Le nommage ou lien vers de fichier ne doit pas être bon car il m'indique "la video n'a pas été trouvée"
cependant j'ai bien les enregistrements dans "/var/www/html/tmp/motion"
-Je n'arrive toujours pas a faire fonctionner le stream j'ai toujours ce message "[DEBUG] : Impossible d'ouvrir le flux video http://192.168.100.112:9999/stream.mjpg" mais le problème de port est résolu.
J'aime beaucoup ton plugin et je sais que c'est beaucoup de travail.
Je suis prêt a t'aider pour debugger. ^^
Cdlt

**Comment by mika-nt28** [comment]
Peux tu poster un screen de ta configuration

**Comment by MarcOlivierChaubet** [comment]
Bonsoir,
voici les screens. J'espere que c'est ce que tu veux.
Cdlt

![conf_motion](https://user-images.githubusercontent.com/32832137/31740064-6513cde4-b450-11e7-9744-0a020186dafb.png)
![conf_cam_motion](https://user-images.githubusercontent.com/32832137/31740138-a998d748-b450-11e7-8493-11814ab15dc6.png)
![conf_cam_filename_motion](https://user-images.githubusercontent.com/32832137/31740179-cf90f1e2-b450-11e7-8330-1259c56485a5.png)

**Comment by mika-nt28** [comment]
C'est l'onglet stream qui m'interesse

**Comment by MarcOlivierChaubet** [comment]
Bonjour, désolé pour ma réponse tardive.
![option stream](https://user-images.githubusercontent.com/32832137/32266618-51707740-bee8-11e7-926c-bb368381c81f.png)
```
: Les coordonées de la détection x=507 y=297 dans =>1208x594
[2017-11-01 09:37:59][DEBUG] : Impossible d'ouvrir le flux video rtsp://admin:********@192.168.100.140:554/11
[2017-11-01 09:37:59][DEBUG] : Impossible d'ouvrir le flux video rtsp://admin:********@192.168.100.44:1111/11
[2017-11-01 09:37:59][DEBUG] : Les coordonées de la détection x=509 y=295 dans =>1218x590
```

**Comment by mika-nt28** [comment]
coche streaming
